import { Project, PunchItem } from '@/types'

export const demoProject: Project = {
  id: 'demo',
  user_id: 'demo-user',
  name: 'Harbor Point Mixed-Use Development',
  address: '1247 Harbor Blvd, San Pedro, CA 90731',
  owner_name: 'Harbor Point LLC',
  general_contractor: 'Pacific Coast Construction',
  retainage_amount: 180000,
  status: 'punchlist',
  created_at: '2024-01-15T08:00:00Z',
}

export const demoPunchItems: PunchItem[] = [
  {
    id: 'demo-item-01',
    project_id: 'demo',
    item_number: 1,
    description: 'Elevator shaft safety railing missing on floors 3-5',
    location: 'Elevator Core',
    trade: 'electrical',
    assigned_to: 'Pacific Elevator Co.',
    assigned_email: 'dispatch@pacificelevator.com',
    priority: 'critical',
    fix_token: 'demo-token-01',
    status: 'open',
    created_at: '2024-01-15T09:00:00Z',
  },
  {
    id: 'demo-item-02',
    project_id: 'demo',
    item_number: 2,
    description: 'Fire suppression head blocked by ductwork in server room',
    location: 'Server Room 101',
    trade: 'HVAC',
    assigned_to: 'SoCal Fire Protection',
    assigned_email: 'service@socalfire.com',
    priority: 'critical',
    fix_token: 'demo-token-02',
    status: 'open',
    created_at: '2024-01-15T09:10:00Z',
  },
  {
    id: 'demo-item-03',
    project_id: 'demo',
    item_number: 3,
    description: 'GFCI outlets not installed in kitchen per code',
    location: 'Unit 204 Kitchen',
    trade: 'electrical',
    assigned_to: 'Westside Electric',
    assigned_email: 'jobs@westsideelectric.com',
    priority: 'high',
    fix_token: 'demo-token-03',
    status: 'open',
    created_at: '2024-01-15T09:20:00Z',
  },
  {
    id: 'demo-item-04',
    project_id: 'demo',
    item_number: 4,
    description: 'Plumbing leak under vanity in master bath',
    location: 'Unit 301 Master Bath',
    trade: 'plumbing',
    assigned_to: 'Harbor Plumbing',
    assigned_email: 'service@harborplumbing.com',
    priority: 'high',
    fix_token: 'demo-token-04',
    status: 'open',
    created_at: '2024-01-15T09:30:00Z',
  },
  {
    id: 'demo-item-05',
    project_id: 'demo',
    item_number: 5,
    description: 'Drywall seams visible at hallway ceiling — needs skim coat',
    location: '3rd Floor Hallway',
    trade: 'drywall',
    assigned_to: 'SoCal Drywall',
    assigned_email: 'work@socaldrywall.com',
    priority: 'high',
    fix_token: 'demo-token-05',
    status: 'open',
    created_at: '2024-01-15T09:40:00Z',
  },
  {
    id: 'demo-item-06',
    project_id: 'demo',
    item_number: 6,
    description: 'Paint touch-up needed at lobby entry wall',
    location: 'Main Lobby',
    trade: 'paint',
    assigned_to: 'Pacific Paint Co.',
    assigned_email: 'jobs@pacificpaint.com',
    priority: 'normal',
    fix_token: 'demo-token-06',
    status: 'open',
    created_at: '2024-01-15T09:50:00Z',
  },
  {
    id: 'demo-item-07',
    project_id: 'demo',
    item_number: 7,
    description: 'Missing outlet cover plate in unit 205',
    location: 'Unit 205',
    trade: 'electrical',
    assigned_to: 'Westside Electric',
    assigned_email: 'jobs@westsideelectric.com',
    priority: 'normal',
    fix_token: 'demo-token-07',
    status: 'open',
    created_at: '2024-01-15T10:00:00Z',
  },
  {
    id: 'demo-item-08',
    project_id: 'demo',
    item_number: 8,
    description: 'Bathroom exhaust fan not working in unit 102',
    location: 'Unit 102 Bath',
    trade: 'HVAC',
    assigned_to: 'SoCal HVAC',
    assigned_email: 'service@socalhvac.com',
    priority: 'normal',
    fix_token: 'demo-token-08',
    status: 'open',
    created_at: '2024-01-15T10:10:00Z',
  },
  {
    id: 'demo-item-09',
    project_id: 'demo',
    item_number: 9,
    description: 'Caulking around tub needs redo in unit 301',
    location: 'Unit 301 Bath',
    trade: 'plumbing',
    assigned_to: 'Harbor Plumbing',
    assigned_email: 'service@harborplumbing.com',
    priority: 'normal',
    fix_token: 'demo-token-09',
    status: 'open',
    created_at: '2024-01-15T10:20:00Z',
  },
  {
    id: 'demo-item-10',
    project_id: 'demo',
    item_number: 10,
    description: 'Ceiling drywall crack in unit 401',
    location: 'Unit 401 Living Room',
    trade: 'drywall',
    assigned_to: 'SoCal Drywall',
    assigned_email: 'work@socaldrywall.com',
    priority: 'normal',
    fix_token: 'demo-token-10',
    status: 'open',
    created_at: '2024-01-15T10:30:00Z',
  },
  {
    id: 'demo-item-11',
    project_id: 'demo',
    item_number: 11,
    description: 'Paint color mismatch on south exterior wall',
    location: 'South Exterior',
    trade: 'paint',
    assigned_to: 'Pacific Paint Co.',
    assigned_email: 'jobs@pacificpaint.com',
    priority: 'normal',
    fix_token: 'demo-token-11',
    status: 'in-progress',
    acknowledged_at: '2024-01-16T08:00:00Z',
    created_at: '2024-01-15T10:40:00Z',
  },
  {
    id: 'demo-item-12',
    project_id: 'demo',
    item_number: 12,
    description: 'Parking lot lighting not functioning — 3 fixtures',
    location: 'Parking Lot B',
    trade: 'electrical',
    assigned_to: 'Westside Electric',
    assigned_email: 'jobs@westsideelectric.com',
    priority: 'normal',
    fix_token: 'demo-token-12',
    status: 'in-progress',
    acknowledged_at: '2024-01-16T09:00:00Z',
    created_at: '2024-01-15T10:50:00Z',
  },
  {
    id: 'demo-item-13',
    project_id: 'demo',
    item_number: 13,
    description: 'Minor drywall ding in unit 203 hallway',
    location: 'Unit 203 Hallway',
    trade: 'drywall',
    assigned_to: 'SoCal Drywall',
    assigned_email: 'work@socaldrywall.com',
    priority: 'normal',
    fix_token: 'demo-token-13',
    status: 'acknowledged',
    acknowledged_at: '2024-01-16T10:00:00Z',
    created_at: '2024-01-15T11:00:00Z',
  },
  {
    id: 'demo-item-14',
    project_id: 'demo',
    item_number: 14,
    description: 'Touch-up paint needed at stairwell handrail',
    location: 'Stairwell B',
    trade: 'paint',
    assigned_to: 'Pacific Paint Co.',
    assigned_email: 'jobs@pacificpaint.com',
    priority: 'low',
    fix_token: 'demo-token-14',
    status: 'resolved',
    acknowledged_at: '2024-01-16T11:00:00Z',
    resolved_at: '2024-01-18T14:00:00Z',
    resolved_by: 'Mike Johnson',
    resolution_notes: 'Touch-up paint applied and dried. Matches existing color.',
    created_at: '2024-01-15T11:10:00Z',
  },
  {
    id: 'demo-item-15',
    project_id: 'demo',
    item_number: 15,
    description: 'Door sweep missing on unit 105 entry',
    location: 'Unit 105',
    trade: 'drywall',
    assigned_to: 'SoCal Drywall',
    assigned_email: 'work@socaldrywall.com',
    priority: 'low',
    fix_token: 'demo-token-15',
    status: 'resolved',
    acknowledged_at: '2024-01-16T12:00:00Z',
    resolved_at: '2024-01-18T15:00:00Z',
    resolved_by: 'Tom Garcia',
    resolution_notes: 'Door sweep installed and tested.',
    created_at: '2024-01-15T11:20:00Z',
  },
  {
    id: 'demo-item-16',
    project_id: 'demo',
    item_number: 16,
    description: 'Window screen missing in unit 202',
    location: 'Unit 202',
    trade: 'drywall',
    assigned_to: 'SoCal Drywall',
    assigned_email: 'work@socaldrywall.com',
    priority: 'normal',
    fix_token: 'demo-token-16',
    status: 'resolved',
    acknowledged_at: '2024-01-17T08:00:00Z',
    resolved_at: '2024-01-19T10:00:00Z',
    resolved_by: 'Tom Garcia',
    resolution_notes: 'Replacement screen installed.',
    created_at: '2024-01-15T11:30:00Z',
  },
  {
    id: 'demo-item-17',
    project_id: 'demo',
    item_number: 17,
    description: 'Smoke detector not responding in unit 301',
    location: 'Unit 301',
    trade: 'electrical',
    assigned_to: 'Westside Electric',
    assigned_email: 'jobs@westsideelectric.com',
    priority: 'normal',
    fix_token: 'demo-token-17',
    status: 'resolved',
    acknowledged_at: '2024-01-17T09:00:00Z',
    resolved_at: '2024-01-19T11:00:00Z',
    resolved_by: 'Sarah Kim',
    resolution_notes: 'Replaced faulty smoke detector. Tested and operational.',
    created_at: '2024-01-15T11:40:00Z',
  },
  {
    id: 'demo-item-18',
    project_id: 'demo',
    item_number: 18,
    description: 'Carpet threshold strip loose at unit 204 entry',
    location: 'Unit 204 Entry',
    trade: 'drywall',
    assigned_to: 'SoCal Drywall',
    assigned_email: 'work@socaldrywall.com',
    priority: 'normal',
    fix_token: 'demo-token-18',
    status: 'resolved',
    acknowledged_at: '2024-01-17T10:00:00Z',
    resolved_at: '2024-01-19T13:00:00Z',
    resolved_by: 'Tom Garcia',
    resolution_notes: 'Threshold strip reattached and secured.',
    created_at: '2024-01-15T11:50:00Z',
  },
]
